### ISSUE TITLE
Road to v2.0.0

### ISSUE THREAD

**Issue by FlorianWoelki** [FlorianWoelki/obsidian-iconize#159]
# v2.0.0

First of all, thank you for your time reading this and for contributing ideas or issues to the plugin or just using it. It's been a long walk for `obsidian-icon-folder`, but it's time to lift things up a bit.

This is the issue for tracking the current state of releasing a significant update.

## What is it about?

The update includes many changes to the internal code because the code was messy in some ways. That's why I've decided to refactor the code to a more usable format. In addition, new features are planned in this update.

## Checklist for new version

- [x] Test and fix internal starred plugin
- [x] Test and fix icons in open file tabs
- [x] Test and fix inheritance
- [x] Test and fix custom rules
- [x] Test and fix custom icon packs
- [x] Test and fix predefined icon packs
- [x] Test and fix styling of icons
- [x] Test and fix emoji icons for all functionalities
- [x] Rename plugin to a more general name and submit to community plugins

## New Features

- [x] Icon in open file tabs #149 

### New Features in later releases:
- [x] New syncing mechanism #153 
- [ ] Right pane icon display #112 

## Issues

- [x] Issue that some icons are not shown correctly #158 
- [x] Same icon for custom rule #141 
- [x] Corrupt icons in icon pack stops loading icon pack completely #160 

## Have other ideas or issues?

If you find any issues with the current code, please feel free to create a new issue. If you have an idea or feature request that should be included in the `v2.0.0`, feel free to post them below this issue.

**Comment by FlorianWoelki** [comment]
Due to new insider builds and `v2.0.0` of obsidian, this plugin's `v2.0.0` update will also force you to update to obsidian `v2.0.0` (there is no compatibility for earlier versions of obsidian). In addition, I'll try to release an early version of `v2.0.0` because there are some issues like #163 or #164. Some features or fixes that are not crucial won't be released in the initial version of `v2.0.0`.
